- README.md
- rwkv/chat_with_bot.py
- rwkv/generate_completions.py
- rwkv/rwkv_cpp_shared_library.py
This updates instructions and works on linux as well. Still couldnt get it to work on Mac M1 due to arm vs x86 mismatch.
> Adds instructions and works on linux as well

- .github/workflows/build.yml
> Update github action to support linux and macos asset uploading

- README.md
Executing the cmake build produces `librwkv.dylib` on MacOS (tested on Ventura 13.3.1), not `rwkv.so` anymore as is still mentioned in the README.
Filename `rwkv.so` got renamed to `librwkv.dylib` as seen in https://github.com/saharNooby/rwkv.cpp/commit/77e19980e9a6c8762037fd45623f2388d67c87b1
> fix: Mention of incorrect filename for MacOS cmake build artifact

- rwkv/chat_with_bot.py
Depending on the localization and language settings of Windows, for example, on Windows 10 when the region is set to China, then Python will read the JSON file in GBK encoding by default when running `rwkv/chat_with_bot.py` (while the encoding of the JSON file is actually UTF-8), resulting in the following error:
```
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 399: illegal multibyte sequence
```
I think it will be better to specify the encoding option when reading prompt data from json.
> Fix encoding issue when loading prompt data

- rwkv.cpp
- rwkv.h
- tests/test_tiny_rwkv.c
Fixes #63
This allows retrieving errors from the library without having to pipe stderr. Also it was annoying that rwkv.cpp assumed control of the caller process by doing things like calling abort() when it shouldn't, so I also fixed that.
The basic way this works is:
1. by default, not much is different, except more errors are caught, and rwkv.cpp should never abort the process or throw a C++ exception.
2. the difference comes when you call rwkv_set_print_errors (working title):
1. errors will no longer be printed to stderr automatically
2. errors will be assigned to a thread-local variable (during init/quantization) or a context-local variable (during eval)
3. the last error can be retrieved using rwkv_get_last_error
I also overhauled the assert macros so more error cases are handled:
- …
> Add rwkv_set_print_errors and rwkv_get_last_error

- rwkv.h
I realized I didn't give enough space for additional failure modes to be added in the future, and I should do this as soon as possible to prevent things from being made that depend on the old constants
> last second move things over in the error enum

- CODE_STYLE.md
- FILE_FORMAT.md
- README.md
- rwkv.cpp
- rwkv.h
- rwkv/chat_with_bot.py
- rwkv/convert_pytorch_to_ggml.py
- rwkv/convert_pytorch_to_ggml.test.py
- rwkv/merge_lora_into_ggml.py
- rwkv/quantize.py
- rwkv/rwkv_cpp_shared_library.py
- tests/test_tiny_rwkv.c
Notable changes:
- `rwkv.cpp` file version was bumped to `101`
- `Q4_2` format was removed
- all other quantized formats were changed in a backwards-incompatible way, older files can not be loaded anymore
> Various improvements & upgrade ggml

- rwkv.cpp
- rwkv.h
- tests/CMakeLists.txt
- tests/test_context_cloning.c
- tests/test_tiny_rwkv.c
This allows for parallel inference and I am preparing to support sequence mode using a method similar to this (creating a new kind of graph)
Yes it should be perfectly safe to mix multiple ggml contexts like this, I looked into the code and there is no requirement that graphs only have to be created from the current context :3
> Allow creating multiple contexts per model

- rwkv/rwkv_tokenizer.py
Previously, the tokenizer would look in the current working directory to find the vocab file. It now looks in the same folder as the python file (so it works regardless of the current working directory).
> Fix bug in world tokenizer

- rwkv.cpp
- rwkv.h
- tests/test_context_cloning.c
- tests/test_tiny_rwkv.c
This could have been done better.
I figured out the secret to declaring backwards-compatibility functions that are no longer in the header file. This doesn't work:
```cpp
RWKV_API extern "C" uint32_t rwkv_get_state_buffer_element_count(const struct rwkv_context * ctx) {
```
This works:
```cpp
extern "C" RWKV_API uint32_t rwkv_get_state_buffer_element_count(const struct rwkv_context * ctx) {
```
So now you know.
For the lulz, I left the python scripts using the old one for now just to show that they work. Let me know if you want those all updated in one go, though I'd prefer to just rework the python scripts completely (I have new bindings that behave a lot better wrt errors).
Anyway, this PR removes `rwkv_get_state_buffer_element_count` and `rwkv_get_logits_buffer_element_count` in favor …
> Phase out very verbose element_count functions

- rwkv.cpp
- rwkv.h
There is no need to calculate logits when it is not necessary, so perform some trickery to avoid calculating that part of the cgraph if logits is not actually going to be used.
Depends on #103
Discussed on https://github.com/saharNooby/rwkv.cpp/issues/106#issuecomment-1605890591
> Elide logits if the logits pointer parameter is NULL

- rwkv.cpp
- rwkv/rwkv_cpp_model.py
- rwkv/rwkv_cpp_shared_library.py
This patch exposes the rwkv_get_n_vocab, rwkv_get_n_embed, rwkv_get_n_layer functions to the Python interface through the n_vocab, n_embed, n_layer properties of the RWKVSharedLibrary class.
> Expose n_vocab, n_embed, n_layer to the Python interface

- .github/workflows/build.yml
- CMakeLists.txt
- rwkv.cpp
Most of the work was getting CMake to find it. Just enable `RWKV_CLBLAST` and then drop the OpenCL & CLBlast distributions into the repository root like so:
the actual folders after unzipping, of course!!
Marked as draft due to lack of testing—I unfortunately lost my bespoke chat script at some point and so can't really do my own experimentation immediately, but I do want to put this out there and have it available for others to see and test out for themselves.
Performance seems to be almost exactly on-par with CUDA in my experience. So maybe this will be getting CUDA-like performance out of Intel and AMD GPUs - exciting :D
It took me about 2 hours and 30 minutes of real time to complete this pull request :)
> Implement basic CLBlast support

- rwkv.cpp
Hi,
This PR fixes when `rwkv_get_system_info_string()` gets called multiples times. The returned string becomes longer and longer.
> only append to cpu string if not initialized

- rwkv_graph.inc
For sequence length = 16, padding memory was decreased from `1024 MB` to `640 MB`.
> Decrease memory padding for serial and sequential contexts

- rwkv.cpp
- rwkv_graph.inc
- rwkv_operators.inc
- rwkv_operators_wkv_v5.inc
Before the change (model is `RWKV-5-World-3B-v2-OnlyForTest_86%25_trained-20231108-ctx4096-Q5_1.bin`):
```
Will allocate 180 MB
CPU, 24 threads, sequence of 1: 89 ms per token
Will allocate 290 MB (sequence_length = 2)
CPU, 24 threads, sequence of 2: 59 ms per token
Will allocate 946 MB (sequence_length = 8)
CPU, 24 threads, sequence of 8: 41 ms per token
Will allocate 3568 MB (sequence_length = 32)
CPU, 24 threads, sequence of 32: 45 ms per token
Will allocate 7064 MB (sequence_length = 64)
CPU, 24 threads, sequence of 64: 49 ms per token
```
After the change:
```
Will allocate 102 MB
CPU, 24 threads, sequence of 1: 70 ms per token
Will allocate 112 MB (sequence_length = 2)
CPU, 24 threads, sequence of 2: 37 ms per token
Will allocate 170 MB (sequence_length = 8)
CPU, 24 threads, …
```
> Add wkv v5 custom operator

- CMakeLists.txt
There are no other references to `BUILD_SHARED_LIBS` so I'm assuming this was a mistake. It won't build on Linux at least due to the lack of `-fPIC` causing linking to fail.
This this change, I was able to successful compile and use the GPU with ROCM.
> Fix: Use correct HIPBLAS shared library flag

- .github/workflows/build.yml
@saharNooby It is my fault. I overlooked that the clang used when building rocm is completely different from the path generated by msvc.
> fix ROCm can't find pack artifacts

- python/merge_lora_into_ggml.py
This pull request fixes a small issue on script `python/merge_lora_into_ggml.py`.
Program should always fail if `arch_version` or data format does not satisfy the preconditions in the program. However, the file `merge_lora_into_ggml.py` uses `assert` statements, sometimes being ignored under high optimization level. We uses `if`-statements here, where those preconditions would always execute, whether the environment enable assert stateuements or not.
Ref: https://stackoverflow.com/questions/61826628/what-is-the-advantage-if-any-of-using-assert-over-an-if-else-condition . Here, our checks are still in effect when `-O` flag is enabled, so `if __debug__:` (implied in `assert` statements) is not necessary.
> fix: use ValueError instead of `assert` on argument checks

- python/chat_with_bot.py
- python/generate_completions.py
- python/measure_pexplexity.py
- python/merge_lora_into_ggml.py
- python/rwkv_cpp/rwkv_cpp_model.py
- python/rwkv_cpp/rwkv_cpp_shared_library.py
- python/rwkv_cpp/rwkv_world_tokenizer.py
- python/sampling.py
- python/tokenizer_util.py
Hi all,
Fixed #165 
Please help review the pull request and suggest edits as needed.
1. I didn’t edit the test files.
2. I'm not sure about the assertions that don't have any string return, so I didn't edit them.
`rwkv_word_tokenizer.py`: line 78-79, 99
`convert_pytorch_to_ggml.py`: line 24
`merge_lora_into_ggml.py`: line 23
edit: I tried to use `if not` to preserve the original logical operation, not sure if this is preferred?
> Fix: Replace all assertions in Python code with if statements

- CMakeLists.txt
- rwkv_graph.inc
- rwkv_operators.inc
This should fix #178 
Edit: Also added a bugfix BTW
> Fix build with CUDA under linux
